# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm init
RUN npm install react
RUN npm install
RUN npm install express
RUN npm install bootstrap
RUN npm install react -bootstrap-icons --save
RUN npm install react-beautiful-dnd
RUN npm install --save-dev @wojtekmaj/enzyme-adapter-react-17
RUN npm install node npm install nodemailer
RUN npm install --save @progress/kendo-react-pdf @progress/kendo-drawing @progress/kendo-licensing
RUN npm install bcrypt
RUN npm install react-icons

# add app
COPY . ./

# start app
CMD ["npm", "start"]

